### ISSUE TITLE
API 设计

### ISSUE THREAD

**Issue by Dafrok** [Dafrok/san-transition#1]
## 设计构想

提供 CSS 钩子~~和可能不需要的常用的 JS 钩子~~，参考 https://github.com/ecomfe/san/issues/115 的讨论，san-transition 暴露一个 transition controller 的工厂方法。延续 0.x 版本的四个 CSS 钩子： `enter` / `before-enter` / `leave` / `before-leave`

## 三个问题

1. 叫什么？
2. 怎么用？
3. 需不需要其它功能？

## 三个备选答案

1. transition
2. 参考下方示例
3. ~~提供 JS 常用钩子，与 CSS 钩子分别打包~~

#### CSS 钩子

```js
import {defineComponent} from 'san'
import {transition} from 'san-transition'

// case 1:
const XComponent = defineComponent({
  template: `<span s-transition="cssHook('fade')"></span>`,
  cssHook: transition
})

// case 2:
const XComponent = defineComponent({
  template: `<span class="x-component" s-transition="fade"></span>`,
  fade: transition('fade')
})

// 列表过渡动画间隔延迟
// case 3:
const XComponent = defineComponent({
  initData () {
    return {list: []}
  }
  template: `<ul>
    <li s-for="item in list" class="x-component" s-transition="cssHook('fade', 1e3)"></li>
  </ul>`,
  cssHook: transition
})
```

```css
.x-component {
  transition: transition all .3s ease-out;
}

.fade-enter, .fade-before-leave {
  /* 这里省略 */
}

.fade-before-enter, .fade-leave  {
  /* 这里省略 */
}
```
